apiVersion: v1
kind: Service
metadata:
  name: chatbot-receiver-gateway
spec:
  type: LoadBalancer
  ports:
    - name: chatbot-receiver-gateway
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: chatbot-receiver-gateway
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: chatbot-receiver-gateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chatbot-receiver-gateway
    spec:
      containers:
        - name: chatbot-receiver
          # e.g. aiqingyuyan/chatbot-receiver:v0.0.2
          image: aiqingyuyan/chatbot-receiver:v0.1.0
          env:
            - name: SLACK_SIGNING_SECRET
              value: $SLACK_SIGNING_SECRET
            - name: BOT_USER_OAUTH_ACCESS_TOKEN
              value: $BOT_USER_OAUTH_ACCESS_TOKEN
          ports:
            - containerPort: 8080
