apiVersion: v1
kind: Service
metadata:
  name: chatbot-receiver-gateway
spec:
  type: LoadBalancer
  ports:
    - name: chatbot-receiver-gateway
      port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: chatbot-receiver-gateway
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: chatbot-receiver-gateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chatbot-receiver-gateway
    spec:
      containers:
        - name: chatbot-receiver
          image: aiqingyuyan/chatbot-receiver:latest
          ports:
            - containerPort: 8000