apiVersion: v1
kind: Service
metadata:
  name: chatbot-receiver-gateway
spec:
  type: LoadBalancer
  ports:
    - name: chatbot-receiver-gateway
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: chatbot-receiver-gateway
