server:
  port: 8000
  servlet:
    context-path: /chatbot

slack:
  signing-secret: \${SLACK_SIGNING_SECRET}
  bot-user-oauth-acces-token: \${BOT_USER_OAUTH_ACCESS_TOKEN}

spring:
  main:
    allow-bean-definition-overriding: true

---
spring.profiles: default

grpc:
  chatbot-service-properties:
    host: localhost
    port: 50051

logging:
  level:
    root: TRACE
    com.github.callibrity.chatbotreceiver: DEBUG

---
spring.profiles: test

# Running on GCP
grpc:
  chatbot-service-properties:
    host: 35.245.228.11
    port: 80

logging:
  level:
    root: DEBUG
    com.github.callibrity.chatbotreceiver: INFO
