name: Branch Test

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install dependencies
      run: go mod download

    - name: Run Unit Test
      run: go test -v ./...
