name: Master Commit

on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install dependencies
      run: go mod download

    - name: Run Unit Test
      run: go test -v ./...

  docker-build:
    name: Build docker image
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      env:
        USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${ USERNAME }/chatbot-receiver:${ GITHUB_SHA }

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
